# SYNCED FROM: ./singapore_api.py
# Canonical copy lives at the repo root. This per-skill copy is kept
# byte-identical (below this header) by scripts/sync_singapore_api.py.
# Do not edit this file by hand — your changes will be overwritten.
#
# To update the shared client:
#   1. Edit ./singapore_api.py (the canonical)
#   2. Run:    python3 scripts/sync_singapore_api.py
#   3. Verify: python3 -m unittest discover -s tests

"""
singapore_api.py — shared data.gov.sg client for all Singapore skills.

This is the canonical copy that lives at the repo root. Per-skill copies at
<skill>/scripts/singapore_api.py are kept byte-identical to this file by
scripts/sync_singapore_api.py (which prepends a SYNCED FROM header). To change
the shared client, edit THIS file, then run:

    python3 scripts/sync_singapore_api.py
    python3 -m unittest discover -s tests

Stdlib only: urllib, gzip, json, os, time, hashlib, pathlib, datetime.

Auth: set DATA_GOV_SG_API_KEY in your environment. The key unlocks the v2
endpoint family (api-open.data.gov.sg/v2/...) which returns flatter payloads
and includes MRT train arrival data not published on v1. v1 endpoints still
work without a key as a fallback. Register at https://data.gov.sg/ to get a
key. The env var is read at call time, not import time, so tests can flip it
freely.

Cache: ~/.hermes/cache/<namespace>/<sha1(key)>.json. The OneMap geocoder is
NOT cached (it's fast and the response is query-specific).

v1 vs v2 routing: most fetchers try v2 first (when a key is set), fall back to
v1 on 401/404/5xx. v2 is the primary path; v1 is the public safety net.
"""
import gzip
import hashlib
import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import math  # for SVY21 → WGS84 conversion


# ── Config ────────────────────────────────────────────────────────────
DATA_GOV_V1 = "https://api.data.gov.sg/v1"
DATA_GOV_V2 = "https://api-open.data.gov.sg/v2/real-time/api"
ONEMAP_SEARCH = "https://www.onemap.gov.sg/api/common/elastic/search"
DATASTORE = "https://data.gov.sg/api/action/datastore_search"  # legacy; new flow uses DATASET_BASE

DATASET_BASE = "https://api-open.data.gov.sg/v1/public/api/datasets"

# Map a v1 path to its v2 equivalent. Endpoints not listed here are v1-only
# (e.g. datastore_search) or v2-only (e.g. mrt-train-arrival).
_V1_TO_V2 = {
    "/environment/psi": "psi",
    "/environment/pm25": "pm25",
    "/environment/uv-index": "uv",
    "/environment/2-hour-weather-forecast": "two-hour-forecast",
    "/environment/24-hour-weather-forecast": "twenty-four-hour-forecast",
    "/environment/4-day-weather-forecast": "four-day-forecast",
    "/environment/rainfall": "rainfall",
    "/environment/wind-speed": "wind",
    "/environment/air-temperature": "temperature",
    "/environment/relative-humidity": "humidity",
    "/transport/traffic-images": "traffic-images",
    "/transport/carpark-availability": "carpark-availability",
    "/transport/bus-eta": "bus-arrival",
    "/transport/taxi-availability": "taxi-availability",
}

CACHE_ROOT = Path(os.path.expanduser("~")) / ".hermes" / "cache"
TIMEOUT_S = 10.0
MAX_ATTEMPTS = 3
BACKOFF_S = (0.5, 1.0, 2.0)  # sleep BEFORE attempts 2, 3, 4 (0-indexed)
USER_AGENT = "singapore-skills/0.1 (+https://github.com/kangcodex/singapore-skills)"

# data.gov.sg Collection/Dataset API IDs. Each ID is the segment after
# /datasets/ in the public URL (e.g.
# https://data.gov.sg/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/view).
# The flow: POST initiate-download (best-effort, swallow auth errors) then
# GET poll-download to retrieve a signed S3 URL, then GET that URL for the
# CSV/GEOJSON body. See fetch_dataset_rows() / fetch_dataset_geojson() below.
HDB_RESALE_DATASET_ID = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc"  # Resale flat prices, CSV, HDB
URA_MASTER_PLAN_DATASET_ID = "d_90d86daa5bfaa371668b84fa5f01424f"  # URA Master Plan 2019 land use, GeoJSON
NEA_RAINFALL_DATASET_ID = "d_b16d06b83473fdfcc92ed9d37b66ba58"  # NEA Rainfall - Monthly Total, CSV
NEA_HAWKER_CENTRES_DATASET_ID = "d_4a086da0a5553be1d89383cd90d07ecd"  # NEA Hawker Centres, GeoJSON
NEA_HAWKER_CLOSURES_DATASET_ID = "d_bda4baa634dd1cc7a6c7cad5f19e2d68"  # NEA Dates of Hawker Centres Closure, CSV
SPORTSG_FACILITIES_DATASET_ID = "d_9b87bab59d036a60fad2a91530e10773"  # SportSG sport facilities, GeoJSON
DENGUE_CLUSTERS_DATASET_ID = "d_dbfabf16158d1b0e1c420627c0819168"  # NEA Dengue Clusters, GeoJSON

# ── Property data layer (S08) ─────────────────────────────────────────
# Property data for the property-advisor-skill v2 (S09a). URA + CEA datasets
# are served via the v2 initiate→poll→signed-S3-URL flow (same as the
# existing fetch_dataset_rows). SINGSTAT datasets are only reachable via
# the legacy CKAN `datastore_search` endpoint — SINGSTAT does not appear
# in the v2 collections catalog. See `docs/api/SINGSTAT.md` for the
# non-v2-access justification.
URA_RENTALS_DATASET_ID = "d_149ac00a2734bb0a03867bbe2ec0e7b0"  # URA coll 1660, Rentals of Non-Landed Residential Buildings, Quarterly
URA_PRIVATE_RESI_TRANS_CENTRAL_DATASET_ID = "d_c287c8be114bfa7d055b27ab2c87de83"  # URA coll 1655, Private Resi Trans in CCR, Quarterly
URA_PRIVATE_RESI_TRANS_OUTSIDE_CENTRAL_DATASET_ID = "d_1a7823f3d31e7db4b426833833762bab"  # URA coll 1656, Private Resi Trans in OCR, Quarterly
URA_PRIVATE_RESI_TRANS_REST_CENTRAL_DATASET_ID = "d_5785799d63a9da091f4e0b456291eeb8"  # URA coll 1657, Private Resi Trans in RCR, Quarterly
URA_PRIVATE_RESI_TRANS_WHOLE_SG_DATASET_ID = "d_7c69c943d5f0d89d6a9a773d2b51f337"  # URA coll 1658, Private Resi Trans Whole SG, Quarterly
URA_EC_SALES_DATASET_ID = "d_19c79027c2e6be3c39d637151bd2188d"  # URA coll 1643, EC Units Launched and Sold, Quarterly
URA_EC_POSITION_DATASET_ID = "d_8b71bc3e1386261039d7ad95efdc3328"  # URA coll 1661, Sale Position of ECs, Quarterly
URA_UNSOLD_PRIVATE_RESI_DATASET_ID = "d_84d05d45049108f0fd2e99b66bd19cfe"  # URA coll 1663, Unsold Private Resi Units, Quarterly
SINGSTAT_SUPPLY_PIPELINE_DATASET_ID = "d_055b6549444dedb341c50805d9682a41"  # SINGSTAT, Supply of Private Resi In Pipeline (legacy CKAN)
SINGSTAT_VACANCY_DATASET_ID = "d_01e3556fb916ca19a7e29fc39520fa78"  # SINGSTAT, Available And Vacant Private Resi (legacy CKAN)
CEA_SALESPERSON_DATASET_ID = "d_07c63be0f37e6e59c07a4ddc2fd87fcb"  # CEA coll 54, Salesperson Information (3x daily)


# ── Cache helpers ─────────────────────────────────────────────────────

def _cache_path(namespace, key):
    """~/.hermes/cache/<namespace>/<sha1(key)>.json. Creates namespace dir."""
    d = CACHE_ROOT / namespace
    d.mkdir(parents=True, exist_ok=True)
    return d / (hashlib.sha1(str(key).encode("utf-8")).hexdigest() + ".json")


def _cache_get(namespace, key):
    """Return cached dict or None. Silently treats corrupt cache as a miss."""
    p = _cache_path(namespace, key)
    if not p.exists():
        return None
    try:
        with open(p, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def _cache_put(namespace, key, payload):
    """Write payload to cache. Silent on OSError — cache is best-effort."""
    p = _cache_path(namespace, key)
    try:
        with open(p, "w", encoding="utf-8") as f:
            json.dump(payload, f)
    except OSError:
        pass


# ── Auth ──────────────────────────────────────────────────────────────

def _api_key():
    """Read DATA_GOV_SG_API_KEY at call time. None when unset."""
    return os.environ.get("DATA_GOV_SG_API_KEY") or None


def require_api_key():
    """Raise a clear error if DATA_GOV_SG_API_KEY is not set. Call this at
    startup for skills that need v2 data (e.g. S04a mrt-rerouter for MRT
    arrival times, which v1 does not publish)."""
    if not _api_key():
        raise RuntimeError(
            "DATA_GOV_SG_API_KEY is not set. Register at https://data.gov.sg/ "
            "to get a key. Some data sources (MRT train arrival) require it."
        )


# ── Core: request_json ────────────────────────────────────────────────

def _do_request(url, headers, namespace, cache_key):
    """Single HTTP attempt. Returns parsed JSON or raises HTTPError/URLError."""
    cached = _cache_get(namespace, cache_key)
    if cached is not None:
        return cached

    last_err = None
    for attempt in range(MAX_ATTEMPTS):
        if attempt > 0:
            time.sleep(BACKOFF_S[attempt - 1])
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
                raw = resp.read()
                if resp.headers.get("Content-Encoding") == "gzip":
                    raw = gzip.decompress(raw)
                body = json.loads(raw)
                _cache_put(namespace, cache_key, body)
                return body
        except urllib.error.HTTPError as e:
            last_err = e
            if e.code == 429 or e.code >= 500:
                continue  # retry
            raise  # 4xx other than 429 → fail fast
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
            last_err = e
            continue  # network/parse → retry

    raise last_err if last_err else RuntimeError("request_json: retries exhausted")


def request_json(url, params=None, namespace=None, extra_headers=None):
    """
    Fetch a JSON payload with auth, caching, retry, and timeout.

    - Cache hit → return immediately, no network.
    - 200 → parse JSON, write to cache, return.
    - 429 / 5xx → retry up to MAX_ATTEMPTS with BACKOFF_S sleeps.
    - Other 4xx → raise urllib.error.HTTPError immediately.
    - Network errors (URLError, TimeoutError, JSONDecodeError) → retry.
    - Raises the last exception after exhausting retries.
    """
    qs = urllib.parse.urlencode(params or {})
    full_url = url + ("?" + qs if qs else "")
    cache_ns = namespace or "default"
    cache_key = full_url

    headers = {
        "Accept-Encoding": "gzip",
        "User-Agent": USER_AGENT,
    }
    key = _api_key()
    if key:
        headers["x-api-key"] = key
    if extra_headers:
        headers.update(extra_headers)

    return _do_request(full_url, headers, cache_ns, cache_key)


def try_v2_then_v1(v1_path, params=None, namespace=None, extra_headers=None):
    """
    Try v2 first (when DATA_GOV_SG_API_KEY is set), fall back to v1 on
    401/404/5xx. Both versions are cached separately.

    Use this for endpoints that exist in both v1 and v2 (most real-time
    environment + transport data). v1-only or v2-only endpoints should call
    request_json() directly.
    """
    cache_ns = namespace or "default"
    key = _api_key()
    v2_endpoint = _V1_TO_V2.get(v1_path)

    qs = urllib.parse.urlencode(params or {})
    headers = {
        "Accept-Encoding": "gzip",
        "User-Agent": USER_AGENT,
    }
    if key:
        headers["x-api-key"] = key
    if extra_headers:
        headers.update(extra_headers)

    # 1) v2 with key
    if key and v2_endpoint:
        v2_url = DATA_GOV_V2 + "/" + v2_endpoint + ("?" + qs if qs else "")
        try:
            return _do_request(v2_url, headers, cache_ns, "v2|" + v2_url)
        except urllib.error.HTTPError as e:
            if e.code not in (401, 403, 404):
                # 5xx or 429: tried MAX_ATTEMPTS times, give up on v2 → fall through to v1
                pass  # fall through to v1
            # 401/403/404: key not authorised, or endpoint not in v2 → fall through to v1
        except (urllib.error.URLError, TimeoutError):
            pass  # network error → fall through to v1

    # 2) v1 fallback
    v1_url = DATA_GOV_V1 + v1_path + ("?" + qs if qs else "")
    # Strip the key header for v1 (v1 doesn't need it; cleaner logs)
    v1_headers = {k: v for k, v in headers.items() if k.lower() != "x-api-key"}
    return _do_request(v1_url, v1_headers, cache_ns, "v1|" + v1_url)


# ── v1 envelope normalisation ─────────────────────────────────────────
# v1 returns nested envelopes (items[].cameras[], items[].carpark_data[].carpark_info[],
# items[].forecasts[]). Skill scripts expect a flat items[] shape, so each
# fetcher that uses v1 normalises before returning. v2 generally returns flat
# shapes already, so v2-fallback callers should not need to re-normalise.

def _flatten_v1_traffic_images(envelope):
    """v1: {items: [{cameras: [{camera_id, image, location, ...}]}]}
    → flat: {items: [{camera_id, image, latitude, longitude, name, timestamp}]}"""
    if not isinstance(envelope, dict):
        return {"items": []}
    flat = []
    for bucket in envelope.get("items") or []:
        for cam in bucket.get("cameras") or []:
            loc = cam.get("location") or {}
            flat.append({
                "camera_id": cam.get("camera_id"),
                "image": cam.get("image"),
                "latitude": loc.get("latitude"),
                "longitude": loc.get("longitude"),
                "name": cam.get("camera_id"),  # v1 has no human label; id is the handle
                "timestamp": cam.get("timestamp"),
            })
    return {"items": flat}


def _flatten_v1_carpark_availability(envelope):
    """v1: {items: [{carpark_data: [{carpark_number, carpark_info: [{lots_available, lot_type, total_lots}]}]}]}
    → flat: {items: [{carpark_id, lots_available, lot_type, total_lots, agency: 'HDB', update_datetime}]}.
    `lots_available` and `total_lots` are strings in v1; coerced to int."""
    if not isinstance(envelope, dict):
        return {"items": []}
    flat = []
    for bucket in envelope.get("items") or []:
        for cd in bucket.get("carpark_data") or []:
            for info in cd.get("carpark_info") or []:
                try:
                    lots = int(info.get("lots_available") or 0)
                except (TypeError, ValueError):
                    lots = 0
                try:
                    total = int(info.get("total_lots") or 0)
                except (TypeError, ValueError):
                    total = 0
                flat.append({
                    "carpark_id": cd.get("carpark_number"),
                    "lots_available": lots,
                    "lot_type": info.get("lot_type"),
                    "total_lots": total,
                    "agency": "HDB",  # v1's carpark-availability is HDB-only
                    "update_datetime": cd.get("update_datetime"),
                })
    return {"items": flat}


def _flatten_v1_two_hour_forecast(envelope):
    """v1: {items: [{forecasts: [{area, forecast}], valid_period, ...}], area_metadata: [...]}
    → flat: {items: [{area, forecast}], valid_period, update_timestamp, area_metadata}.
    Keeps `area_metadata` so callers can geocode an area name if needed."""
    if not isinstance(envelope, dict):
        return {"items": []}
    out = {"items": [], "area_metadata": envelope.get("area_metadata") or []}
    for bucket in envelope.get("items") or []:
        out["items"].extend(bucket.get("forecasts") or [])
        if "valid_period" in bucket and "valid_period" not in out:
            out["valid_period"] = bucket["valid_period"]
        if "update_timestamp" in bucket and "update_timestamp" not in out:
            out["update_timestamp"] = bucket["update_timestamp"]
    return out


# ── Real-time fetchers (try v2 first, fall back to v1) ────────────────
# Each fetcher returns a normalised dict. v1 envelopes are flattened in
# _flatten_v1_* helpers; v2 returns a flatter shape that's returned as-is.

def fetch_pm25():
    """PM2.5 readings, 1-hour average."""
    return try_v2_then_v1("/environment/pm25", namespace="pm25")


def fetch_psi():
    """Pollutant Standards Index, per NEA region (5 regions: national, central,
    east, west, north, south)."""
    return try_v2_then_v1("/environment/psi", namespace="psi")


def fetch_uv():
    """UV index, single national reading."""
    return try_v2_then_v1("/environment/uv-index", namespace="uv")


def fetch_two_hour_forecast():
    """NEA 2-hour weather forecast (text). Returned envelope is normalised to
    `items: [{area, forecast}]` plus the original `area_metadata`."""
    return _flatten_v1_two_hour_forecast(
        try_v2_then_v1("/environment/2-hour-weather-forecast", namespace="two-hour-forecast")
    )


def fetch_twenty_four_hour_forecast():
    """NEA 24-hour weather forecast (text + temp range)."""
    return try_v2_then_v1("/environment/24-hour-weather-forecast", namespace="twenty-four-hour-forecast")


def fetch_four_day_forecast():
    """NEA 4-day weather outlook."""
    return try_v2_then_v1("/environment/4-day-weather-forecast", namespace="four-day-forecast")


def fetch_rainfall():
    """Real-time rainfall readings across NEA stations."""
    return try_v2_then_v1("/environment/rainfall", namespace="rainfall")


def fetch_wind():
    """Real-time wind direction + speed across NEA stations."""
    return try_v2_then_v1("/environment/wind-speed", namespace="wind")


def fetch_temperature():
    """Real-time air temperature across NEA stations."""
    return try_v2_then_v1("/environment/air-temperature", namespace="temperature")


def fetch_humidity():
    """Real-time relative humidity across NEA stations."""
    return try_v2_then_v1("/environment/relative-humidity", namespace="humidity")


def fetch_lta_traffic_images():
    """LTA traffic camera snapshots. Returned envelope is normalised to
    `items: [{camera_id, image, latitude, longitude, name, timestamp}]`."""
    return _flatten_v1_traffic_images(
        try_v2_then_v1("/transport/traffic-images", namespace="traffic-images")
    )


def fetch_hdb_carpark_availability():
    """HDB carpark lots available. Returned envelope is normalised to
    `items: [{carpark_id, lots_available, lot_type, total_lots, agency, update_datetime}]`.
    `lots_available` is an int (v1 sends it as a string)."""
    return _flatten_v1_carpark_availability(
        try_v2_then_v1("/transport/carpark-availability", namespace="carpark-availability")
    )


def fetch_lta_bus_arrival(bus_stop_code=None, service_no=None):
    """LTA bus arrival times. v2 takes BusStopCode + ServiceNo as query params.
    When called without args, fetches a generic list (may 400 on v1; v2 is more
    forgiving). S04a (mrt-rerouter) parameterises this directly."""
    params = {}
    if bus_stop_code:
        params["BusStopCode"] = bus_stop_code
    if service_no:
        params["ServiceNo"] = service_no
    return try_v2_then_v1("/transport/bus-eta", params=params, namespace="bus-arrival")


def fetch_lta_mrt_arrival(station_code=None):
    """LTA MRT train arrival times. v2-only (v1 does not publish MRT data);
    DATA_GOV_SG_API_KEY is required. Callers that need MRT data should check
    the env var first or catch the RuntimeError raised when the key is missing.

    `station_code` (e.g. 'NS1' for Marina South Pier) is passed as a query
    param when set.
    """
    require_api_key()
    params = {}
    if station_code:
        params["StationCode"] = station_code
    qs = urllib.parse.urlencode(params)
    url = DATA_GOV_V2 + "/mrt-train-arrival" + ("?" + qs if qs else "")
    headers = {
        "Accept-Encoding": "gzip",
        "User-Agent": USER_AGENT,
        "x-api-key": _api_key(),
    }
    return _do_request(url, headers, "mrt-arrival", "v2|" + url)


def fetch_lta_taxi_availability():
    """LTA taxi availability by zone (GeoJSON-style coordinates)."""
    return try_v2_then_v1("/transport/taxi-availability", namespace="taxi-availability")


# ── CKAN datastore helpers (static datasets) ──────────────────────────
# Most non-real-time data.gov.sg datasets are served via the CKAN
# `datastore_search` action on a separate host (no /v1, no /v2, no auth).
# Each call paginates with limit+offset; total count comes back as
# result.total. The resource_id (UUID) is dataset-specific — discover via
# `https://data.gov.sg/api/action/package_show?id=<name>` and pick the
# resource where `datastore_active` is true.

def fetch_datastore_search(resource_id, limit=100, offset=0, filters=None):
    """Legacy CKAN stub. data.gov.sg no longer uses CKAN. See
    fetch_dataset_rows() / fetch_dataset_geojson() for the v2 download flow.
    """
    raise NotImplementedError("CKAN deprecated; use fetch_dataset_rows")


def _dataset_headers():
    """Headers required by data.gov.sg initiate-download and poll-download.
    Verified live: missing either header → HTTP 403. The x-api-key value comes
    from the DATA_GOV_SG_API_KEY env var (v2 key, registered at data.gov.sg).
    """
    h = {
        "User-Agent": USER_AGENT,
        "Content-Type": "application/json",
    }
    key = os.environ.get("DATA_GOV_SG_API_KEY")
    if key:
        h["x-api-key"] = key
    return h


def fetch_dataset_rows(dataset_id, filters=None):
    """Generic data.gov.sg dataset fetch (CSV → list of row dicts).

    Flow:
      1. POST initiate-download (best-effort, swallow auth errors)
      2. GET poll-download → signed S3 URL
      3. GET the URL → CSV body
      4. Parse with csv.DictReader, return list[dict]
    """
    import csv as _csv
    import io as _io

    namespace = "dataset:%s" % dataset_id
    if filters:
        import hashlib
        key = repr(filters) if isinstance(filters, (list, tuple)) else repr(sorted(filters.items()))
        h = hashlib.sha1(key.encode("utf-8")).hexdigest()[:12]
        namespace = "dataset:%s:%s" % (dataset_id, h)

    cached = _cache_get(namespace, "rows")
    if cached is not None:
        return cached

    try:
        req = urllib.request.Request(
            "%s/%s/initiate-download" % (DATASET_BASE, dataset_id),
            data=b"{}",
            headers=_dataset_headers(),
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp.read()
    except Exception:
        pass

    poll_req = urllib.request.Request(
        "%s/%s/poll-download" % (DATASET_BASE, dataset_id),
        headers=_dataset_headers(),
    )
    with urllib.request.urlopen(poll_req, timeout=15) as resp:
        envelope = json.loads(resp.read())
    url = envelope.get("data", {}).get("url")
    if not url:
        return []

    with urllib.request.urlopen(url, timeout=30) as resp:
        body = resp.read()

    text = body.decode("utf-8-sig", errors="replace")
    rows = list(_csv.DictReader(_io.StringIO(text)))
    _cache_put(namespace, "rows", rows)
    return rows


def fetch_dataset_geojson(dataset_id):
    """data.gov.sg dataset fetch (GeoJSON → parsed FeatureCollection dict)."""
    namespace = "dataset-geojson:%s" % dataset_id

    cached = _cache_get(namespace, "geojson")
    if cached is not None:
        return cached

    try:
        req = urllib.request.Request(
            "%s/%s/initiate-download" % (DATASET_BASE, dataset_id),
            data=b"{}",
            headers=_dataset_headers(),
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            resp.read()
    except Exception:
        pass

    poll_req = urllib.request.Request(
        "%s/%s/poll-download" % (DATASET_BASE, dataset_id),
        headers=_dataset_headers(),
    )
    with urllib.request.urlopen(poll_req, timeout=15) as resp:
        envelope = json.loads(resp.read())
    url = envelope.get("data", {}).get("url")
    if not url:
        return {"type": "FeatureCollection", "features": []}

    with urllib.request.urlopen(url, timeout=30) as resp:
        body = resp.read().decode("utf-8-sig", errors="replace")

    parsed = json.loads(body)
    _cache_put(namespace, "geojson", parsed)
    return parsed


def fetch_ura_master_plan():
    """URA Master Plan Land Use layer (planning boundaries + future amenity
    sites). Returns the raw CKAN envelope — callers iterate `result.records`
    and apply category classification to `lu_desc` / `mpro_use` fields.

    URA records carry SVY21 geometry; the S02a skill uses `planning_area`
    string match (no coord math) for town-level filtering.
    """
    return fetch_dataset_geojson(URA_MASTER_PLAN_DATASET_ID)


def fetch_nea_historical_rainfall(station_id=None, months=24):
    """NEA monthly rainfall totals. When `station_id` is set, filters to that
    station. Default 24-month window.

    Records are returned newest-first — callers reverse if they want
    chronological order.
    """
    filters = None
    if station_id:
        filters = [{"columnName": "station_id", "type": "EQ", "value": station_id}]
    return fetch_dataset_rows(NEA_RAINFALL_DATASET_ID, filters=filters)


def fetch_hawker_closures():
    """NEA hawker centres with quarterly cleaning schedule. Returns the full
    CKAN envelope — every hawker centre, not just those currently closed.

    Each record carries `name`, `lat`, `lon`, and a `next_closure_start` /
    `next_closure_end` window (ISO date strings). Callers decide "closed now"
    by comparing the dates to today, and find open alternates by excluding
    entries whose window covers today. Shared between S03a (weekend-planner)
    and S06a (hawker-discover) — both filter the same way.
    """
    return fetch_dataset_rows(NEA_HAWKER_CLOSURES_DATASET_ID)


def fetch_activesg_facilities():
    """ActiveSG facilities nationwide. Returns the full CKAN envelope.

    Each record carries `name`, `lat`, `lon`, `indoor` (bool), and
    `facility_type` (e.g. SWIMMING, GYM, SPORTS_HALL). Callers pick the
    nearest indoor facility by haversine as a UV / PSI pivot.
    """
    return fetch_dataset_geojson(SPORTSG_FACILITIES_DATASET_ID)


def fetch_dengue_clusters():
    """NEA dengue cluster locations. Returns the full CKAN envelope.

    Each record carries `town`, `street`, `lat`, `lon`, `n_cases`,
    `alert_level` (HIGH/ALERT/CASUAL), `as_of_date`. Callers filter by
    haversine to the user's location to find clusters within ~1 km.
    Total record count is ~100 active clusters at any time.
    """
    return fetch_dataset_geojson(DENGUE_CLUSTERS_DATASET_ID)


# ── Property data layer (S08) ─────────────────────────────────────────
# Eight fetchers supporting the property-advisor-skill v2 (S09a). URA + CEA
# use the v2 dataset flow; SINGSTAT uses the legacy CKAN endpoint because
# SINGSTAT datasets are not in the v2 collections catalog. All follow the
# existing convention: env-key auth (DATA_GOV_SG_API_KEY), no-auth fallback,
# cache via the request_json() cache_namespace, no top-level network.

URA_REGION_DATASET_IDS = {
    "central": URA_PRIVATE_RESI_TRANS_CENTRAL_DATASET_ID,
    "outside_central": URA_PRIVATE_RESI_TRANS_OUTSIDE_CENTRAL_DATASET_ID,
    "rest_central": URA_PRIVATE_RESI_TRANS_REST_CENTRAL_DATASET_ID,
    "whole_sg": URA_PRIVATE_RESI_TRANS_WHOLE_SG_DATASET_ID,
}


def _normalize_qtr_label(s):
    """Normalise a SINGSTAT quarter column name to "YYYY-Q#".

    Observed input shapes: "20261Q", "2025 4Q", "2025-Q3", "2025q3".
    Unrecognised strings are returned unchanged so the caller can decide
    whether to keep or drop them.
    """
    if not isinstance(s, str):
        return s
    s = s.strip()
    m = re.match(r"^(\d{4})([1-4])Q$", s)
    if m:
        return "%s-Q%s" % (m.group(1), m.group(2))
    m = re.match(r"^(\d{4})[-\s]?[qQ]([1-4])$", s)
    if m:
        return "%s-Q%s" % (m.group(1), m.group(2))
    m = re.match(r"^(\d{4})[-\s]([1-4])[qQ]$", s)
    if m:
        return "%s-Q%s" % (m.group(1), m.group(2))
    return s


def _pivot_quarterly_wide(records):
    """Pivot SINGSTAT wide-format records `[{DataSeries, "20261Q": 100, ...}]`
    to long format `[{series, qtr, value}]`.

    The `DataSeries` column carries the series name. Every other column
    (other than `_id`) is treated as a quarter, normalised via
    `_normalize_qtr_label`, and converted to float. Non-numeric values
    (empty cells, "n/a") are dropped.
    """
    if not records:
        return []
    out = []
    for r in records:
        series = r.get("DataSeries") or r.get("data_series")
        if not series:
            continue
        for col, val in r.items():
            if col in ("DataSeries", "data_series", "_id"):
                continue
            qtr = _normalize_qtr_label(col)
            if qtr == col:
                continue
            try:
                fval = float(val)
            except (TypeError, ValueError):
                continue
            out.append({"series": str(series).strip(), "qtr": qtr, "value": fval})
    return out


def _fetch_singstat_ckan(resource_id, limit=10000):
    """Fetch all records from a SINGSTAT dataset via legacy CKAN.

    SINGSTAT is not in the v2 collections catalog; the public
    `datastore_search` endpoint still works for these resource IDs. Limit
    10000 is the documented CKAN maximum. The SINGSTAT datasets we call
    have at most ~30 records, so a single call is sufficient.
    """
    ns = "singstat-ckan:%s" % resource_id
    cached = _cache_get(ns, "rows")
    if cached is not None:
        return cached
    url = "%s?resource_id=%s&limit=%d" % (DATASTORE, resource_id, limit)
    try:
        body = request_json(url, namespace=ns)
    except Exception:
        return []
    records = (body.get("result") or {}).get("records") or []
    _cache_put(ns, "rows", records)
    return records


def fetch_ura_rentals():
    """URA Rentals of Non-Landed Residential Buildings, quarterly (coll 1660).

    Dataset: `URA_RENTALS_DATASET_ID` (`d_149ac00a2734bb0a03867bbe2ec0e7b0`).
    Returns a list of CSV row dicts. Typical columns: `qtr`, `region`,
    `property_type`, `median_rent_psf_pm`, `median_rent`.
    """
    return fetch_dataset_rows(URA_RENTALS_DATASET_ID)


def fetch_ura_private_resi_trans(region):
    """URA Private Residential Property Transactions, quarterly, by region.

    `region` ∈ `{"whole_sg", "central", "rest_central", "outside_central"}`.
    Raises ValueError on any other value. The four regions are served by
    four distinct URA collections (1655–1658); see `URA_REGION_DATASET_IDS`.

    Returns CSV row dicts; typical columns: `qtr`, `district`,
    `property_type`, `sale_count`, `median_psf`, `median_trans_price`.
    """
    if region not in URA_REGION_DATASET_IDS:
        raise ValueError(
            "fetch_ura_private_resi_trans: region %r not in %s"
            % (region, sorted(URA_REGION_DATASET_IDS))
        )
    return fetch_dataset_rows(URA_REGION_DATASET_IDS[region])


def fetch_ura_ec_sales():
    """URA Executive Condominium Units Launched and Sold, quarterly (coll 1643).

    Dataset: `URA_EC_SALES_DATASET_ID` (`d_19c79027c2e6be3c39d637151bd2188d`).
    Returns CSV row dicts; typical columns: `qtr`, `ec_name`, `units_launched`,
    `units_sold`.
    """
    return fetch_dataset_rows(URA_EC_SALES_DATASET_ID)


def fetch_ura_ec_position():
    """URA Sale Position of Executive Condominiums, quarterly (coll 1661).

    Dataset: `URA_EC_POSITION_DATASET_ID`
    (`d_8b71bc3e1386261039d7ad95efdc3328`). Returns CSV row dicts; typical
    columns: `qtr`, `ec_name`, `units_unsold`, `launch_year`.
    """
    return fetch_dataset_rows(URA_EC_POSITION_DATASET_ID)


def fetch_ura_unsold_private_resi():
    """URA Unsold Private Residential Units, quarterly (coll 1663).

    Dataset: `URA_UNSOLD_PRIVATE_RESI_DATASET_ID`
    (`d_84d05d45049108f0fd2e99b66bd19cfe`). This collection has 0
    childDatasets in the v2 catalog metadata, but the dataset itself is
    reachable via the v2 initiate-poll flow (verified 2026-06-22, 948
    records, columns include `quarter` and `unsold_units`).

    Returns CSV row dicts; typical columns: `quarter`, `market_segment`,
    `unsold_units`.
    """
    return fetch_dataset_rows(URA_UNSOLD_PRIVATE_RESI_DATASET_ID)


def fetch_singstat_supply_pipeline():
    """SINGSTAT Supply Of Private Residential Properties In The Pipeline.

    Dataset: `SINGSTAT_SUPPLY_PIPELINE_DATASET_ID`
    (`d_055b6549444dedb341c50805d9682a41`). SINGSTAT is not in the v2
    collections catalog; this fetcher uses the legacy CKAN
    `datastore_search` endpoint and pivots the wide `DataSeries × quarter`
    shape to long format. Returns `[{series, qtr, value}]` with ~10 series
    (e.g. "In Planning", "Under Construction", "Completed").
    """
    records = _fetch_singstat_ckan(SINGSTAT_SUPPLY_PIPELINE_DATASET_ID)
    return _pivot_quarterly_wide(records)


def fetch_singstat_vacancy():
    """SINGSTAT Available And Vacant Private Residential Properties.

    Dataset: `SINGSTAT_VACANCY_DATASET_ID`
    (`d_01e3556fb916ca19a7e29fc39520fa78`). SINGSTAT is not in the v2
    collections catalog; legacy CKAN + wide-to-long pivot. Returns
    `[{series, qtr, value}]` with ~6 series (e.g. "Available", "Vacant").
    """
    records = _fetch_singstat_ckan(SINGSTAT_VACANCY_DATASET_ID)
    return _pivot_quarterly_wide(records)


def fetch_cea_salesperson(query):
    """CEA Salesperson Information, refreshed 3x daily (coll 54).

    Dataset: `CEA_SALESPERSON_DATASET_ID`
    (`d_07c63be0f37e6e59c07a4ddc2fd87fcb`). `query` is either a
    registration number (case-insensitive exact match, e.g. "R012345X") or
    a name fragment (case-insensitive substring match). Empty/None query
    returns `[]`.

    Returns a list of CSV row dicts; typical columns: `registration_no`,
    `name`, `status`, `agency`.
    """
    if not query:
        return []
    q = str(query).strip().lower()
    if not q:
        return []
    rows = fetch_dataset_rows(CEA_SALESPERSON_DATASET_ID)
    if q.startswith("r") and len(q) >= 3:
        return [r for r in rows if str(r.get("registration_no", "")).strip().lower() == q]
    return [r for r in rows if q in str(r.get("name", "")).lower()]


# ── SVY21 → WGS84 ─────────────────────────────────────────────────────
# Singapore uses SVY21 (a Transverse Mercator projection) for cadastral
# data. URA Master Plan records carry geometry in SVY21 easting/northing;
# callers that need lat/lon go through svy21_to_wgs84().

def svy21_to_wgs84(easting, northing):
    """Convert SVY21 projected coordinates (meters) to WGS84 lat/lon.

    Inverse Transverse Mercator using Singapore Land Authority parameters.
    Returns (lat, lon) in degrees. Accurate to ~1m across mainland SG —
    good enough for "is this amenity within walking distance?" judgments.
    """
    a = 6378137.0
    f = 1.0 / 298.257223563
    k0 = 1.0
    lat0 = math.radians(1.366666)  # 1°22' N
    lon0 = math.radians(103.833333)  # 103°50' E
    e0 = 28001.642  # false easting (Singapore Land Authority)
    n0 = 38744.572  # false northing (Singapore Land Authority)
    e2 = 2.0 * f - f * f
    e_prime_sq = e2 / (1.0 - e2)
    n_val = a / math.sqrt(1.0 - e2 * math.sin(lat0) ** 2)

    # Meridional arc
    m0 = a * (
        (1.0 - e2 / 4.0 - 3.0 * e2 ** 2 / 64.0 - 5.0 * e2 ** 3 / 256.0) * lat0
        - (3.0 * e2 / 8.0 + 3.0 * e2 ** 2 / 32.0 + 45.0 * e2 ** 3 / 1024.0) * math.sin(2.0 * lat0)
        + (15.0 * e2 ** 2 / 256.0 + 45.0 * e2 ** 3 / 1024.0) * math.sin(4.0 * lat0)
        - (35.0 * e2 ** 3 / 3072.0) * math.sin(6.0 * lat0)
    )
    m = m0 + (northing - n0) / k0

    # Footprint latitude
    e1 = (1.0 - math.sqrt(1.0 - e2)) / (1.0 + math.sqrt(1.0 - e2))
    mu = m / (a * (1.0 - e2 / 4.0 - 3.0 * e2 ** 2 / 64.0 - 5.0 * e2 ** 3 / 256.0))
    phi1 = (
        mu
        + (3.0 * e1 / 2.0 - 27.0 * e1 ** 3 / 32.0) * math.sin(2.0 * mu)
        + (21.0 * e1 ** 2 / 16.0 - 55.0 * e1 ** 4 / 32.0) * math.sin(4.0 * mu)
        + (151.0 * e1 ** 3 / 96.0) * math.sin(6.0 * mu)
    )
    t1 = math.tan(phi1) ** 2
    c1 = e_prime_sq * math.cos(phi1) ** 2
    r1 = a * (1.0 - e2) / (1.0 - e2 * math.sin(phi1) ** 2) ** 1.5
    d_val = (easting - e0) / (n_val * k0)
    phi = (
        phi1
        - (n_val * math.tan(phi1) / r1)
        * (d_val ** 2 / 2.0
           - (5.0 + 3.0 * t1 + 10.0 * c1 - 4.0 * c1 ** 2 - 9.0 * e_prime_sq) * d_val ** 4 / 24.0
           + (61.0 + 90.0 * t1 + 298.0 * c1 + 45.0 * t1 ** 2 - 252.0 * e_prime_sq
              - 3.0 * c1 ** 2) * d_val ** 6 / 720.0)
    )
    lam = (
        lon0
        + (d_val
           - (1.0 + 2.0 * t1 + c1) * d_val ** 3 / 6.0
           + (5.0 - 2.0 * c1 + 28.0 * t1 - 3.0 * c1 ** 2 + 8.0 * e_prime_sq
              + 24.0 * t1 ** 2) * d_val ** 5 / 120.0) / math.cos(phi1)
    )
    return math.degrees(phi), math.degrees(lam)


def haversine_m(lat1, lon1, lat2, lon2):
    """Great-circle distance in metres between two WGS84 points. Returns
    None if any input is None (graceful degradation when an upstream record
    has missing coordinates — caller checks for None before using the result)."""
    if None in (lat1, lon1, lat2, lon2):
        return None
    r = 6371000.0  # Earth radius, metres
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (
        math.sin(dlat / 2.0) ** 2
        + math.cos(math.radians(lat1))
        * math.cos(math.radians(lat2))
        * math.sin(dlon / 2.0) ** 2
    )
    return 2.0 * r * math.asin(min(1.0, math.sqrt(a)))


# ── Tier / classification helpers (pure, no I/O) ────────────────────

HEAVY_RAIN_KEYWORDS = ("heavy thundery showers", "thundery showers", "heavy rain")


def is_heavy_rain(weather_payload):
    """True when any item in a v1/v2 two-hour-forecast payload contains a
    heavy-rain keyword in its `forecast` string. Shared by mrt-rerouter and
    the S07 orchestration chain."""
    if not isinstance(weather_payload, dict):
        return False
    items = weather_payload.get("items") or []
    for item in items:
        if not isinstance(item, dict):
            continue
        forecast = (item.get("forecast") or "").lower()
        for kw in HEAVY_RAIN_KEYWORDS:
            if kw in forecast:
                return True
    return False


def psi_tier(reading):
    """Map a national 24h PSI reading to its NEA tier.

    good <= 50, moderate 51-100, unhealthy 101-200, hazardous >= 201.
    None -> "unknown".
    """
    if reading is None:
        return "unknown"
    if reading <= 50:
        return "good"
    if reading <= 100:
        return "moderate"
    if reading <= 200:
        return "unhealthy"
    return "hazardous"


def psi_national(psi_payload):
    """Drill the 24h national PSI out of a v1/v2 PSI payload. Returns int
    (NEA publishes whole numbers) or None on missing/garbage data.

    v1 includes a `national` key in psi_twenty_four_hourly; v2 omits it and
    reports per-region values. We use the max of any numeric values as the
    national reading, matching NEA's convention of reporting the worst region
    as the headline PSI.
    """
    if not isinstance(psi_payload, dict):
        return None
    items = psi_payload.get("items")
    if items is None:
        items = (psi_payload.get("data") or {}).get("items")
    if not items or not isinstance(items[0], dict):
        return None
    readings = items[0].get("readings") or {}
    if not isinstance(readings, dict):
        return None
    psi24 = readings.get("psi_twenty_four_hourly") or {}
    if not isinstance(psi24, dict) or not psi24:
        return None
    try:
        return int(max(int(v) for v in psi24.values() if isinstance(v, (int, float))))
    except (TypeError, ValueError):
        return None


# ── OneMap geocoder (NOT cached) ──────────────────────────────────────

def geocode(query):
    """
    Resolve a Singapore place name / postal to (address, lat, lon, postal).

    OneMap quirk: the response includes
        "error": "Authentication token missing"
    even when results[] is populated. We ignore the error field and read from
    results[0].

    Returns (address: str, lat: float, lon: float, postal: str | None).
    Raises ValueError when results[] is empty.
    """
    body = request_json(
        ONEMAP_SEARCH,
        params={"searchVal": query, "returnGeom": "Y", "getAddrDetails": "Y", "pageNum": "1"},
        namespace="onemap-geocode",
    )
    results = body.get("results") or []
    if not results:
        raise ValueError("geocode: no results for %r" % (query,))
    first = results[0]
    return (
        first.get("ADDRESS", ""),
        float(first["LATITUDE"]),
        float(first["LONGITUDE"]),
        first.get("POSTAL") or None,
    )


# ── CLI smoke test ───────────────────────────────────────────────────

if __name__ == "__main__":
    # `python3 singapore_api.py` → quick sanity check that the module loads
    # and reports routing state. Useful for first-run diagnosis.
    print(json.dumps({
        "module": "singapore_api",
        "fetchers": [
            "fetch_pm25", "fetch_psi", "fetch_uv",
            "fetch_two_hour_forecast", "fetch_twenty_four_hour_forecast",
            "fetch_four_day_forecast",
            "fetch_rainfall", "fetch_wind", "fetch_temperature", "fetch_humidity",
            "fetch_lta_traffic_images", "fetch_hdb_carpark_availability",
            "fetch_lta_bus_arrival", "fetch_lta_mrt_arrival", "fetch_lta_taxi_availability",
            "fetch_datastore_search", "fetch_ura_master_plan", "fetch_nea_historical_rainfall",
        ],
        "geocode": "OneMap public (free, no auth)",
        "auth": "DATA_GOV_SG_API_KEY (v2 enabled)" if _api_key() else "DATA_GOV_SG_API_KEY unset (v1 only)",
        "routing": "v2 first when key set, v1 fallback",
        "datastore": "CKAN action=datastore_search (no auth)",
    }, indent=2))
