#!/usr/bin/env python3
"""
scripts/sync_singapore_api.py — keep per-skill copies of singapore_api.py in sync.

The canonical file lives at the repo root: ./singapore_api.py
Per-skill copies live at:   <skill>/scripts/singapore_api.py

Each per-skill copy is the canonical file with a 5-line SYNCED FROM header
prepended. The header is required so the copies are self-documenting
("don't edit me — edit the canonical").

Usage:
    python3 scripts/sync_singapore_api.py            # copy to all skills
    python3 scripts/sync_singapore_api.py --check    # exit 1 if any copy is stale
    python3 scripts/sync_singapore_api.py --dry-run  # show what would change

Add a new skill to SKILL_FOLDERS when you create a new <skill>/ folder.
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = REPO_ROOT / "singapore_api.py"

# Order matches PRD-S00 / INDEX dependency order. Add new skills here.
SKILL_FOLDERS = [
    "cdc-voucher-locator-skill",
    "smart-commuter-skill",
    "resale-property-advisor-skill",
    "weekend-planner-skill",
    "mrt-rerouter-skill",
    "dengue-risk-advisor-skill",
    "hawker-discover-skill",
]

SYNC_HEADER = """# SYNCED FROM: ./singapore_api.py
# Canonical copy lives at the repo root. This per-skill copy is kept
# byte-identical (below this header) by scripts/sync_singapore_api.py.
# Do not edit this file by hand — your changes will be overwritten.
#
# To update the shared client:
#   1. Edit ./singapore_api.py (the canonical)
#   2. Run:    python3 scripts/sync_singapore_api.py
#   3. Verify: python3 -m unittest discover -s tests

"""


def per_skill_path(skill_folder):
    return REPO_ROOT / skill_folder / "scripts" / "singapore_api.py"


def build_body():
    """Read the canonical file, prepend the SYNCED FROM header."""
    canonical_text = CANONICAL.read_text(encoding="utf-8")
    return SYNC_HEADER + canonical_text


def sync(skill_folder, body, *, dry_run):
    """Write per-skill copy. Returns True if changed (or would be, in dry-run)."""
    target = per_skill_path(skill_folder)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.read_text(encoding="utf-8") == body:
        return False
    if not dry_run:
        target.write_text(body, encoding="utf-8")
    return True


def main(argv):
    args = set(argv[1:])
    check_only = "--check" in args
    dry_run = "--dry-run" in args

    if not CANONICAL.exists():
        print("ERROR: canonical file not found at %s" % CANONICAL, file=sys.stderr)
        return 2

    body = build_body()
    changed, missing = [], []

    for skill in SKILL_FOLDERS:
        if not (REPO_ROOT / skill).is_dir():
            missing.append(skill)
            continue
        if sync(skill, body, dry_run=dry_run or check_only):
            changed.append(skill)

    if missing:
        print("NOTE: %d skill folder(s) not yet created (will be skipped):" % len(missing))
        for s in missing:
            print("  - %s" % s)

    if check_only:
        if changed:
            print("STALE: %d per-skill copy/ies out of sync:" % len(changed))
            for s in changed:
                print("  - %s/scripts/singapore_api.py" % s)
            print("Run: python3 scripts/sync_singapore_api.py")
            return 1
        ok_count = len(SKILL_FOLDERS) - len(missing)
        print("OK: all %d per-skill copy/ies match canonical." % ok_count)
        return 0

    if dry_run:
        if changed:
            print("Would update %d per-skill copy/ies:" % len(changed))
            for s in changed:
                print("  - %s/scripts/singapore_api.py" % s)
        else:
            print("All per-skill copies already match.")
        return 0

    if changed:
        print("Synced %d per-skill copy/ies: %s" % (len(changed), ", ".join(changed)))
    else:
        print("All per-skill copies already match.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
